#include "timezones.h"
#include "pgmspace.h"

// Keep strings to fixed length. Workaround for memory leaks
// https://github.com/espressif/esp-idf/issues/3046
static const char * timezoneList[] PROGMEM = {
    "GMT0                                                                                               ", // Africa_Abidjan
    "GMT0                                                                                               ", // Africa_Accra
    "EAT-3                                                                                              ", // Africa_Addis_Ababa
    "CET-1                                                                                              ", // Africa_Algiers
    "EAT-3                                                                                              ", // Africa_Asmara
    "EAT-3                                                                                              ", // Africa_Asmera
    "GMT0                                                                                               ", // Africa_Bamako
    "WAT-1                                                                                              ", // Africa_Bangui
    "GMT0                                                                                               ", // Africa_Banjul
    "GMT0                                                                                               ", // Africa_Bissau
    "CAT-2                                                                                              ", // Africa_Blantyre
    "WAT-1                                                                                              ", // Africa_Brazzaville
    "CAT-2                                                                                              ", // Africa_Bujumbura
    "EET-2                                                                                              ", // Africa_Cairo
    "<+01>-1                                                                                            ", // Africa_Casablanca
    "CET-1CEST,M3.5.0,M10.5.0/3                                                                         ", // Africa_Ceuta
    "GMT0                                                                                               ", // Africa_Conakry
    "GMT0                                                                                               ", // Africa_Dakar
    "EAT-3                                                                                              ", // Africa_Dar_es_Salaam
    "EAT-3                                                                                              ", // Africa_Djibouti
    "WAT-1                                                                                              ", // Africa_Douala
    "<+01>-1                                                                                            ", // Africa_El_Aaiun
    "GMT0                                                                                               ", // Africa_Freetown
    "CAT-2                                                                                              ", // Africa_Gaborone
    "CAT-2                                                                                              ", // Africa_Harare
    "SAST-2                                                                                             ", // Africa_Johannesburg
    "CAT-2                                                                                              ", // Africa_Juba
    "EAT-3                                                                                              ", // Africa_Kampala
    "CAT-2                                                                                              ", // Africa_Khartoum
    "CAT-2                                                                                              ", // Africa_Kigali
    "WAT-1                                                                                              ", // Africa_Kinshasa
    "WAT-1                                                                                              ", // Africa_Lagos
    "WAT-1                                                                                              ", // Africa_Libreville
    "GMT0                                                                                               ", // Africa_Lome
    "WAT-1                                                                                              ", // Africa_Luanda
    "CAT-2                                                                                              ", // Africa_Lubumbashi
    "CAT-2                                                                                              ", // Africa_Lusaka
    "WAT-1                                                                                              ", // Africa_Malabo
    "CAT-2                                                                                              ", // Africa_Maputo
    "SAST-2                                                                                             ", // Africa_Maseru
    "SAST-2                                                                                             ", // Africa_Mbabane
    "EAT-3                                                                                              ", // Africa_Mogadishu
    "GMT0                                                                                               ", // Africa_Monrovia
    "EAT-3                                                                                              ", // Africa_Nairobi
    "WAT-1                                                                                              ", // Africa_Ndjamena
    "WAT-1                                                                                              ", // Africa_Niamey
    "GMT0                                                                                               ", // Africa_Nouakchott
    "GMT0                                                                                               ", // Africa_Ouagadougou
    "WAT-1                                                                                              ", // Africa_Porto_Novo
    "GMT0                                                                                               ", // Africa_Sao_Tome
    "GMT0                                                                                               ", // Africa_Timbuktu
    "EET-2                                                                                              ", // Africa_Tripoli
    "CET-1                                                                                              ", // Africa_Tunis
    "CAT-2                                                                                              ", // Africa_Windhoek
    "HST10HDT,M3.2.0,M11.1.0                                                                            ", // America_Adak
    "AKST9AKDT,M3.2.0,M11.1.0                                                                           ", // America_Anchorage
    "AST4                                                                                               ", // America_Anguilla
    "AST4                                                                                               ", // America_Antigua
    "<-03>3                                                                                             ", // America_Araguaina
    "AST4                                                                                               ", // America_Aruba
    "<-04>4<-03>,M10.1.0/0,M3.4.0/0                                                                     ", // America_Asuncion
    "EST5                                                                                               ", // America_Atikokan
    "HST10HDT,M3.2.0,M11.1.0                                                                            ", // America_Atka
    "<-03>3                                                                                             ", // America_Bahia
    "CST6CDT,M4.1.0,M10.5.0                                                                             ", // America_Bahia_Banderas
    "AST4                                                                                               ", // America_Barbados
    "<-03>3                                                                                             ", // America_Belem
    "CST6                                                                                               ", // America_Belize
    "AST4                                                                                               ", // America_Blanc_Sablon
    "<-04>4                                                                                             ", // America_Boa_Vista
    "<-05>5                                                                                             ", // America_Bogota
    "MST7MDT,M3.2.0,M11.1.0                                                                             ", // America_Boise
    "<-03>3                                                                                             ", // America_Buenos_Aires
    "MST7MDT,M3.2.0,M11.1.0                                                                             ", // America_Cambridge_Bay
    "<-04>4                                                                                             ", // America_Campo_Grande
    "EST5                                                                                               ", // America_Cancun
    "<-04>4                                                                                             ", // America_Caracas
    "<-03>3                                                                                             ", // America_Catamarca
    "<-03>3                                                                                             ", // America_Cayenne
    "EST5                                                                                               ", // America_Cayman
    "CST6CDT,M3.2.0,M11.1.0                                                                             ", // America_Chicago
    "MST7MDT,M4.1.0,M10.5.0                                                                             ", // America_Chihuahua
    "EST5                                                                                               ", // America_Coral_Harbour
    "<-03>3                                                                                             ", // America_Cordoba
    "CST6                                                                                               ", // America_Costa_Rica
    "MST7                                                                                               ", // America_Creston
    "<-04>4                                                                                             ", // America_Cuiaba
    "AST4                                                                                               ", // America_Curacao
    "GMT0                                                                                               ", // America_Danmarkshavn
    "MST7                                                                                               ", // America_Dawson
    "MST7                                                                                               ", // America_Dawson_Creek
    "MST7MDT,M3.2.0,M11.1.0                                                                             ", // America_Denver
    "EST5EDT,M3.2.0,M11.1.0                                                                             ", // America_Detroit
    "AST4                                                                                               ", // America_Dominica
    "MST7MDT,M3.2.0,M11.1.0                                                                             ", // America_Edmonton
    "<-05>5                                                                                             ", // America_Eirunepe
    "CST6                                                                                               ", // America_El_Salvador
    "PST8PDT,M3.2.0,M11.1.0                                                                             ", // America_Ensenada
    "MST7                                                                                               ", // America_Fort_Nelson
    "EST5EDT,M3.2.0,M11.1.0                                                                             ", // America_Fort_Wayne
    "<-03>3                                                                                             ", // America_Fortaleza
    "AST4ADT,M3.2.0,M11.1.0                                                                             ", // America_Glace_Bay
    "<-03>3<-02>,M3.5.0/-2,M10.5.0/-1                                                                   ", // America_Godthab
    "AST4ADT,M3.2.0,M11.1.0                                                                             ", // America_Goose_Bay
    "EST5EDT,M3.2.0,M11.1.0                                                                             ", // America_Grand_Turk
    "AST4                                                                                               ", // America_Grenada
    "AST4                                                                                               ", // America_Guadeloupe
    "CST6                                                                                               ", // America_Guatemala
    "<-05>5                                                                                             ", // America_Guayaquil
    "<-04>4                                                                                             ", // America_Guyana
    "AST4ADT,M3.2.0,M11.1.0                                                                             ", // America_Halifax
    "CST5CDT,M3.2.0/0,M11.1.0/1                                                                         ", // America_Havana
    "MST7                                                                                               ", // America_Hermosillo
    "EST5EDT,M3.2.0,M11.1.0                                                                             ", // America_Indianapolis
    "MST7MDT,M3.2.0,M11.1.0                                                                             ", // America_Inuvik
    "EST5EDT,M3.2.0,M11.1.0                                                                             ", // America_Iqaluit
    "EST5                                                                                               ", // America_Jamaica
    "<-03>3                                                                                             ", // America_Jujuy
    "AKST9AKDT,M3.2.0,M11.1.0                                                                           ", // America_Juneau
    "CST6CDT,M3.2.0,M11.1.0                                                                             ", // America_Knox_IN
    "AST4                                                                                               ", // America_Kralendijk
    "<-04>4                                                                                             ", // America_La_Paz
    "<-05>5                                                                                             ", // America_Lima
    "PST8PDT,M3.2.0,M11.1.0                                                                             ", // America_Los_Angeles
    "EST5EDT,M3.2.0,M11.1.0                                                                             ", // America_Louisville
    "AST4                                                                                               ", // America_Lower_Princes
    "<-03>3                                                                                             ", // America_Maceio
    "CST6                                                                                               ", // America_Managua
    "<-04>4                                                                                             ", // America_Manaus
    "AST4                                                                                               ", // America_Marigot
    "AST4                                                                                               ", // America_Martinique
    "CST6CDT,M3.2.0,M11.1.0                                                                             ", // America_Matamoros
    "MST7MDT,M4.1.0,M10.5.0                                                                             ", // America_Mazatlan
    "<-03>3                                                                                             ", // America_Mendoza
    "CST6CDT,M3.2.0,M11.1.0                                                                             ", // America_Menominee
    "CST6CDT,M4.1.0,M10.5.0                                                                             ", // America_Merida
    "AKST9AKDT,M3.2.0,M11.1.0                                                                           ", // America_Metlakatla
    "CST6CDT,M4.1.0,M10.5.0                                                                             ", // America_Mexico_City
    "<-03>3<-02>,M3.2.0,M11.1.0                                                                         ", // America_Miquelon
    "AST4ADT,M3.2.0,M11.1.0                                                                             ", // America_Moncton
    "CST6CDT,M4.1.0,M10.5.0                                                                             ", // America_Monterrey
    "<-03>3                                                                                             ", // America_Montevideo
    "EST5EDT,M3.2.0,M11.1.0                                                                             ", // America_Montreal
    "AST4                                                                                               ", // America_Montserrat
    "EST5EDT,M3.2.0,M11.1.0                                                                             ", // America_Nassau
    "EST5EDT,M3.2.0,M11.1.0                                                                             ", // America_New_York
    "EST5EDT,M3.2.0,M11.1.0                                                                             ", // America_Nipigon
    "AKST9AKDT,M3.2.0,M11.1.0                                                                           ", // America_Nome
    "<-02>2                                                                                             ", // America_Noronha
    "<-03>3<-02>,M3.5.0/-2,M10.5.0/-1                                                                   ", // America_Nuuk
    "MST7MDT,M3.2.0,M11.1.0                                                                             ", // America_Ojinaga
    "EST5                                                                                               ", // America_Panama
    "EST5EDT,M3.2.0,M11.1.0                                                                             ", // America_Pangnirtung
    "<-03>3                                                                                             ", // America_Paramaribo
    "MST7                                                                                               ", // America_Phoenix
    "EST5EDT,M3.2.0,M11.1.0                                                                             ", // America_Port_au_Prince
    "AST4                                                                                               ", // America_Port_of_Spain
    "<-05>5                                                                                             ", // America_Porto_Acre
    "<-04>4                                                                                             ", // America_Porto_Velho
    "AST4                                                                                               ", // America_Puerto_Rico
    "<-03>3                                                                                             ", // America_Punta_Arenas
    "CST6CDT,M3.2.0,M11.1.0                                                                             ", // America_Rainy_River
    "CST6CDT,M3.2.0,M11.1.0                                                                             ", // America_Rankin_Inlet
    "<-03>3                                                                                             ", // America_Recife
    "CST6                                                                                               ", // America_Regina
    "CST6CDT,M3.2.0,M11.1.0                                                                             ", // America_Resolute
    "<-05>5                                                                                             ", // America_Rio_Branco
    "<-03>3                                                                                             ", // America_Rosario
    "PST8PDT,M3.2.0,M11.1.0                                                                             ", // America_Santa_Isabel
    "<-03>3                                                                                             ", // America_Santarem
    "<-04>4<-03>,M9.1.6/24,M4.1.6/24                                                                    ", // America_Santiago
    "AST4                                                                                               ", // America_Santo_Domingo
    "<-03>3                                                                                             ", // America_Sao_Paulo
    "<-01>1<+00>,M3.5.0/0,M10.5.0/1                                                                     ", // America_Scoresbysund
    "MST7MDT,M3.2.0,M11.1.0                                                                             ", // America_Shiprock
    "AKST9AKDT,M3.2.0,M11.1.0                                                                           ", // America_Sitka
    "AST4                                                                                               ", // America_St_Barthelemy
    "NST3:30NDT,M3.2.0,M11.1.0                                                                          ", // America_St_Johns
    "AST4                                                                                               ", // America_St_Kitts
    "AST4                                                                                               ", // America_St_Lucia
    "AST4                                                                                               ", // America_St_Thomas
    "AST4                                                                                               ", // America_St_Vincent
    "CST6                                                                                               ", // America_Swift_Current
    "CST6                                                                                               ", // America_Tegucigalpa
    "AST4ADT,M3.2.0,M11.1.0                                                                             ", // America_Thule
    "EST5EDT,M3.2.0,M11.1.0                                                                             ", // America_Thunder_Bay
    "PST8PDT,M3.2.0,M11.1.0                                                                             ", // America_Tijuana
    "EST5EDT,M3.2.0,M11.1.0                                                                             ", // America_Toronto
    "AST4                                                                                               ", // America_Tortola
    "PST8PDT,M3.2.0,M11.1.0                                                                             ", // America_Vancouver
    "AST4                                                                                               ", // America_Virgin
    "MST7                                                                                               ", // America_Whitehorse
    "CST6CDT,M3.2.0,M11.1.0                                                                             ", // America_Winnipeg
    "AKST9AKDT,M3.2.0,M11.1.0                                                                           ", // America_Yakutat
    "MST7MDT,M3.2.0,M11.1.0                                                                             ", // America_Yellowknife
    "<+11>-11                                                                                           ", // Antarctica_Casey
    "<+07>-7                                                                                            ", // Antarctica_Davis
    "<+10>-10                                                                                           ", // Antarctica_DumontDUrville
    "AEST-10AEDT,M10.1.0,M4.1.0/3                                                                       ", // Antarctica_Macquarie
    "<+05>-5                                                                                            ", // Antarctica_Mawson
    "NZST-12NZDT,M9.5.0,M4.1.0/3                                                                        ", // Antarctica_McMurdo
    "<-03>3                                                                                             ", // Antarctica_Palmer
    "<-03>3                                                                                             ", // Antarctica_Rothera
    "NZST-12NZDT,M9.5.0,M4.1.0/3                                                                        ", // Antarctica_South_Pole
    "<+03>-3                                                                                            ", // Antarctica_Syowa
    "<+00>0<+02>-2,M3.5.0/1,M10.5.0/3                                                                   ", // Antarctica_Troll
    "<+06>-6                                                                                            ", // Antarctica_Vostok
    "CET-1CEST,M3.5.0,M10.5.0/3                                                                         ", // Arctic_Longyearbyen
    "<+03>-3                                                                                            ", // Asia_Aden
    "<+06>-6                                                                                            ", // Asia_Almaty
    "EET-2EEST,M2.5.4/24,M10.5.5/1                                                                      ", // Asia_Amman
    "<+12>-12                                                                                           ", // Asia_Anadyr
    "<+05>-5                                                                                            ", // Asia_Aqtau
    "<+05>-5                                                                                            ", // Asia_Aqtobe
    "<+05>-5                                                                                            ", // Asia_Ashgabat
    "<+05>-5                                                                                            ", // Asia_Ashkhabad
    "<+05>-5                                                                                            ", // Asia_Atyrau
    "<+03>-3                                                                                            ", // Asia_Baghdad
    "<+03>-3                                                                                            ", // Asia_Bahrain
    "<+04>-4                                                                                            ", // Asia_Baku
    "<+07>-7                                                                                            ", // Asia_Bangkok
    "<+07>-7                                                                                            ", // Asia_Barnaul
    "EET-2EEST,M3.5.0/0,M10.5.0/0                                                                       ", // Asia_Beirut
    "<+06>-6                                                                                            ", // Asia_Bishkek
    "<+08>-8                                                                                            ", // Asia_Brunei
    "IST-5:30                                                                                           ", // Asia_Calcutta
    "<+09>-9                                                                                            ", // Asia_Chita
    "<+08>-8                                                                                            ", // Asia_Choibalsan
    "CST-8                                                                                              ", // Asia_Chongqing
    "CST-8                                                                                              ", // Asia_Chungking
    "<+0530>-5:30                                                                                       ", // Asia_Colombo
    "<+06>-6                                                                                            ", // Asia_Dacca
    "EET-2EEST,M3.5.5/0,M10.5.5/0                                                                       ", // Asia_Damascus
    "<+06>-6                                                                                            ", // Asia_Dhaka
    "<+09>-9                                                                                            ", // Asia_Dili
    "<+04>-4                                                                                            ", // Asia_Dubai
    "<+05>-5                                                                                            ", // Asia_Dushanbe
    "EET-2EEST,M3.5.0/3,M10.5.0/4                                                                       ", // Asia_Famagusta
    "EET-2EEST,M3.4.4/48,M10.5.5/1                                                                      ", // Asia_Gaza
    "CST-8                                                                                              ", // Asia_Harbin
    "EET-2EEST,M3.4.4/48,M10.5.5/1                                                                      ", // Asia_Hebron
    "<+07>-7                                                                                            ", // Asia_Ho_Chi_Minh
    "HKT-8                                                                                              ", // Asia_Hong_Kong
    "<+07>-7                                                                                            ", // Asia_Hovd
    "<+08>-8                                                                                            ", // Asia_Irkutsk
    "<+03>-3                                                                                            ", // Asia_Istanbul
    "WIB-7                                                                                              ", // Asia_Jakarta
    "WIT-9                                                                                              ", // Asia_Jayapura
    "IST-2IDT,M3.4.4/26,M10.5.0                                                                         ", // Asia_Jerusalem
    "<+0430>-4:30                                                                                       ", // Asia_Kabul
    "<+12>-12                                                                                           ", // Asia_Kamchatka
    "PKT-5                                                                                              ", // Asia_Karachi
    "<+06>-6                                                                                            ", // Asia_Kashgar
    "<+0545>-5:45                                                                                       ", // Asia_Kathmandu
    "<+0545>-5:45                                                                                       ", // Asia_Katmandu
    "<+09>-9                                                                                            ", // Asia_Khandyga
    "IST-5:30                                                                                           ", // Asia_Kolkata
    "<+07>-7                                                                                            ", // Asia_Krasnoyarsk
    "<+08>-8                                                                                            ", // Asia_Kuala_Lumpur
    "<+08>-8                                                                                            ", // Asia_Kuching
    "<+03>-3                                                                                            ", // Asia_Kuwait
    "CST-8                                                                                              ", // Asia_Macao
    "CST-8                                                                                              ", // Asia_Macau
    "<+11>-11                                                                                           ", // Asia_Magadan
    "WITA-8                                                                                             ", // Asia_Makassar
    "PST-8                                                                                              ", // Asia_Manila
    "<+04>-4                                                                                            ", // Asia_Muscat
    "EET-2EEST,M3.5.0/3,M10.5.0/4                                                                       ", // Asia_Nicosia
    "<+07>-7                                                                                            ", // Asia_Novokuznetsk
    "<+07>-7                                                                                            ", // Asia_Novosibirsk
    "<+06>-6                                                                                            ", // Asia_Omsk
    "<+05>-5                                                                                            ", // Asia_Oral
    "<+07>-7                                                                                            ", // Asia_Phnom_Penh
    "WIB-7                                                                                              ", // Asia_Pontianak
    "KST-9                                                                                              ", // Asia_Pyongyang
    "<+03>-3                                                                                            ", // Asia_Qatar
    "<+06>-6                                                                                            ", // Asia_Qostanay
    "<+05>-5                                                                                            ", // Asia_Qyzylorda
    "<+0630>-6:30                                                                                       ", // Asia_Rangoon
    "<+03>-3                                                                                            ", // Asia_Riyadh
    "<+07>-7                                                                                            ", // Asia_Saigon
    "<+11>-11                                                                                           ", // Asia_Sakhalin
    "<+05>-5                                                                                            ", // Asia_Samarkand
    "KST-9                                                                                              ", // Asia_Seoul
    "CST-8                                                                                              ", // Asia_Shanghai
    "<+08>-8                                                                                            ", // Asia_Singapore
    "<+11>-11                                                                                           ", // Asia_Srednekolymsk
    "CST-8                                                                                              ", // Asia_Taipei
    "<+05>-5                                                                                            ", // Asia_Tashkent
    "<+04>-4                                                                                            ", // Asia_Tbilisi
    "<+0330>-3:30<+0430>,J79/24,J263/24                                                                 ", // Asia_Tehran
    "IST-2IDT,M3.4.4/26,M10.5.0                                                                         ", // Asia_Tel_Aviv
    "<+06>-6                                                                                            ", // Asia_Thimbu
    "<+06>-6                                                                                            ", // Asia_Thimphu
    "JST-9                                                                                              ", // Asia_Tokyo
    "<+07>-7                                                                                            ", // Asia_Tomsk
    "WITA-8                                                                                             ", // Asia_Ujung_Pandang
    "<+08>-8                                                                                            ", // Asia_Ulaanbaatar
    "<+08>-8                                                                                            ", // Asia_Ulan_Bator
    "<+06>-6                                                                                            ", // Asia_Urumqi
    "<+10>-10                                                                                           ", // Asia_Ust_Nera
    "<+07>-7                                                                                            ", // Asia_Vientiane
    "<+10>-10                                                                                           ", // Asia_Vladivostok
    "<+09>-9                                                                                            ", // Asia_Yakutsk
    "<+0630>-6:30                                                                                       ", // Asia_Yangon
    "<+05>-5                                                                                            ", // Asia_Yekaterinburg
    "<+04>-4                                                                                            ", // Asia_Yerevan
    "<-01>1<+00>,M3.5.0/0,M10.5.0/1                                                                     ", // Atlantic_Azores
    "AST4ADT,M3.2.0,M11.1.0                                                                             ", // Atlantic_Bermuda
    "WET0WEST,M3.5.0/1,M10.5.0                                                                          ", // Atlantic_Canary
    "<-01>1                                                                                             ", // Atlantic_Cape_Verde
    "WET0WEST,M3.5.0/1,M10.5.0                                                                          ", // Atlantic_Faeroe
    "WET0WEST,M3.5.0/1,M10.5.0                                                                          ", // Atlantic_Faroe
    "CET-1CEST,M3.5.0,M10.5.0/3                                                                         ", // Atlantic_Jan_Mayen
    "WET0WEST,M3.5.0/1,M10.5.0                                                                          ", // Atlantic_Madeira
    "GMT0                                                                                               ", // Atlantic_Reykjavik
    "<-02>2                                                                                             ", // Atlantic_South_Georgia
    "GMT0                                                                                               ", // Atlantic_St_Helena
    "<-03>3                                                                                             ", // Atlantic_Stanley
    "AEST-10AEDT,M10.1.0,M4.1.0/3                                                                       ", // Australia_ACT
    "ACST-9:30ACDT,M10.1.0,M4.1.0/3                                                                     ", // Australia_Adelaide
    "AEST-10                                                                                            ", // Australia_Brisbane
    "ACST-9:30ACDT,M10.1.0,M4.1.0/3                                                                     ", // Australia_Broken_Hill
    "AEST-10AEDT,M10.1.0,M4.1.0/3                                                                       ", // Australia_Canberra
    "AEST-10AEDT,M10.1.0,M4.1.0/3                                                                       ", // Australia_Currie
    "ACST-9:30                                                                                          ", // Australia_Darwin
    "<+0845>-8:45                                                                                       ", // Australia_Eucla
    "AEST-10AEDT,M10.1.0,M4.1.0/3                                                                       ", // Australia_Hobart
    "<+1030>-10:30<+11>-11,M10.1.0,M4.1.0                                                               ", // Australia_LHI
    "AEST-10                                                                                            ", // Australia_Lindeman
    "<+1030>-10:30<+11>-11,M10.1.0,M4.1.0                                                               ", // Australia_Lord_Howe
    "AEST-10AEDT,M10.1.0,M4.1.0/3                                                                       ", // Australia_Melbourne
    "AEST-10AEDT,M10.1.0,M4.1.0/3                                                                       ", // Australia_NSW
    "ACST-9:30                                                                                          ", // Australia_North
    "AWST-8                                                                                             ", // Australia_Perth
    "AEST-10                                                                                            ", // Australia_Queensland
    "ACST-9:30ACDT,M10.1.0,M4.1.0/3                                                                     ", // Australia_South
    "AEST-10AEDT,M10.1.0,M4.1.0/3                                                                       ", // Australia_Sydney
    "AEST-10AEDT,M10.1.0,M4.1.0/3                                                                       ", // Australia_Tasmania
    "AEST-10AEDT,M10.1.0,M4.1.0/3                                                                       ", // Australia_Victoria
    "AWST-8                                                                                             ", // Australia_West
    "ACST-9:30ACDT,M10.1.0,M4.1.0/3                                                                     ", // Australia_Yancowinna
    "<-05>5                                                                                             ", // Brazil_Acre
    "<-02>2                                                                                             ", // Brazil_DeNoronha
    "<-03>3                                                                                             ", // Brazil_East
    "<-04>4                                                                                             ", // Brazil_West
    "AST4ADT,M3.2.0,M11.1.0                                                                             ", // Canada_Atlantic
    "CST6CDT,M3.2.0,M11.1.0                                                                             ", // Canada_Central
    "EST5EDT,M3.2.0,M11.1.0                                                                             ", // Canada_Eastern
    "MST7MDT,M3.2.0,M11.1.0                                                                             ", // Canada_Mountain
    "NST3:30NDT,M3.2.0,M11.1.0                                                                          ", // Canada_Newfoundland
    "PST8PDT,M3.2.0,M11.1.0                                                                             ", // Canada_Pacific
    "CST6                                                                                               ", // Canada_Saskatchewan
    "MST7                                                                                               ", // Canada_Yukon
    "<-04>4<-03>,M9.1.6/24,M4.1.6/24                                                                    ", // Chile_Continental
    "<-06>6<-05>,M9.1.6/22,M4.1.6/22                                                                    ", // Chile_EasterIsland
    "GMT0                                                                                               ", // Etc_GMT
    "GMT0                                                                                               ", // Etc_GMT0
    "GMT0                                                                                               ", // Etc_GMT_0
    "<+01>-1                                                                                            ", // Etc_GMT_1
    "<+10>-10                                                                                           ", // Etc_GMT_10
    "<+11>-11                                                                                           ", // Etc_GMT_11
    "<+12>-12                                                                                           ", // Etc_GMT_12
    "<+13>-13                                                                                           ", // Etc_GMT_13
    "<+14>-14                                                                                           ", // Etc_GMT_14
    "<+02>-2                                                                                            ", // Etc_GMT_2
    "<+03>-3                                                                                            ", // Etc_GMT_3
    "<+04>-4                                                                                            ", // Etc_GMT_4
    "<+05>-5                                                                                            ", // Etc_GMT_5
    "<+06>-6                                                                                            ", // Etc_GMT_6
    "<+07>-7                                                                                            ", // Etc_GMT_7
    "<+08>-8                                                                                            ", // Etc_GMT_8
    "<+09>-9                                                                                            ", // Etc_GMT_9
    "GMT0                                                                                               ", // Etc_GMTp0
    "<-01>1                                                                                             ", // Etc_GMTp1
    "<-10>10                                                                                            ", // Etc_GMTp10
    "<-11>11                                                                                            ", // Etc_GMTp11
    "<-12>12                                                                                            ", // Etc_GMTp12
    "<-02>2                                                                                             ", // Etc_GMTp2
    "<-03>3                                                                                             ", // Etc_GMTp3
    "<-04>4                                                                                             ", // Etc_GMTp4
    "<-05>5                                                                                             ", // Etc_GMTp5
    "<-06>6                                                                                             ", // Etc_GMTp6
    "<-07>7                                                                                             ", // Etc_GMTp7
    "<-08>8                                                                                             ", // Etc_GMTp8
    "<-09>9                                                                                             ", // Etc_GMTp9
    "GMT0                                                                                               ", // Etc_Greenwich
    "UTC0                                                                                               ", // Etc_UCT
    "UTC0                                                                                               ", // Etc_UTC
    "UTC0                                                                                               ", // Etc_Universal
    "UTC0                                                                                               ", // Etc_Zulu
    "CET-1CEST,M3.5.0,M10.5.0/3                                                                         ", // Europe_Amsterdam
    "CET-1CEST,M3.5.0,M10.5.0/3                                                                         ", // Europe_Andorra
    "<+04>-4                                                                                            ", // Europe_Astrakhan
    "EET-2EEST,M3.5.0/3,M10.5.0/4                                                                       ", // Europe_Athens
    "GMT0BST,M3.5.0/1,M10.5.0                                                                           ", // Europe_Belfast
    "CET-1CEST,M3.5.0,M10.5.0/3                                                                         ", // Europe_Belgrade
    "CET-1CEST,M3.5.0,M10.5.0/3                                                                         ", // Europe_Berlin
    "CET-1CEST,M3.5.0,M10.5.0/3                                                                         ", // Europe_Bratislava
    "CET-1CEST,M3.5.0,M10.5.0/3                                                                         ", // Europe_Brussels
    "EET-2EEST,M3.5.0/3,M10.5.0/4                                                                       ", // Europe_Bucharest
    "CET-1CEST,M3.5.0,M10.5.0/3                                                                         ", // Europe_Budapest
    "CET-1CEST,M3.5.0,M10.5.0/3                                                                         ", // Europe_Busingen
    "EET-2EEST,M3.5.0,M10.5.0/3                                                                         ", // Europe_Chisinau
    "CET-1CEST,M3.5.0,M10.5.0/3                                                                         ", // Europe_Copenhagen
    "IST-1GMT0,M10.5.0,M3.5.0/1                                                                         ", // Europe_Dublin
    "CET-1CEST,M3.5.0,M10.5.0/3                                                                         ", // Europe_Gibraltar
    "GMT0BST,M3.5.0/1,M10.5.0                                                                           ", // Europe_Guernsey
    "EET-2EEST,M3.5.0/3,M10.5.0/4                                                                       ", // Europe_Helsinki
    "GMT0BST,M3.5.0/1,M10.5.0                                                                           ", // Europe_Isle_of_Man
    "<+03>-3                                                                                            ", // Europe_Istanbul
    "GMT0BST,M3.5.0/1,M10.5.0                                                                           ", // Europe_Jersey
    "EET-2                                                                                              ", // Europe_Kaliningrad
    "EET-2EEST,M3.5.0/3,M10.5.0/4                                                                       ", // Europe_Kiev
    "<+03>-3                                                                                            ", // Europe_Kirov
    "WET0WEST,M3.5.0/1,M10.5.0                                                                          ", // Europe_Lisbon
    "CET-1CEST,M3.5.0,M10.5.0/3                                                                         ", // Europe_Ljubljana
    "GMT0BST,M3.5.0/1,M10.5.0                                                                           ", // Europe_London
    "CET-1CEST,M3.5.0,M10.5.0/3                                                                         ", // Europe_Luxembourg
    "CET-1CEST,M3.5.0,M10.5.0/3                                                                         ", // Europe_Madrid
    "CET-1CEST,M3.5.0,M10.5.0/3                                                                         ", // Europe_Malta
    "EET-2EEST,M3.5.0/3,M10.5.0/4                                                                       ", // Europe_Mariehamn
    "<+03>-3                                                                                            ", // Europe_Minsk
    "CET-1CEST,M3.5.0,M10.5.0/3                                                                         ", // Europe_Monaco
    "MSK-3                                                                                              ", // Europe_Moscow
    "EET-2EEST,M3.5.0/3,M10.5.0/4                                                                       ", // Europe_Nicosia
    "CET-1CEST,M3.5.0,M10.5.0/3                                                                         ", // Europe_Oslo
    "CET-1CEST,M3.5.0,M10.5.0/3                                                                         ", // Europe_Paris
    "CET-1CEST,M3.5.0,M10.5.0/3                                                                         ", // Europe_Podgorica
    "CET-1CEST,M3.5.0,M10.5.0/3                                                                         ", // Europe_Prague
    "EET-2EEST,M3.5.0/3,M10.5.0/4                                                                       ", // Europe_Riga
    "CET-1CEST,M3.5.0,M10.5.0/3                                                                         ", // Europe_Rome
    "<+04>-4                                                                                            ", // Europe_Samara
    "CET-1CEST,M3.5.0,M10.5.0/3                                                                         ", // Europe_San_Marino
    "CET-1CEST,M3.5.0,M10.5.0/3                                                                         ", // Europe_Sarajevo
    "<+04>-4                                                                                            ", // Europe_Saratov
    "MSK-3                                                                                              ", // Europe_Simferopol
    "CET-1CEST,M3.5.0,M10.5.0/3                                                                         ", // Europe_Skopje
    "EET-2EEST,M3.5.0/3,M10.5.0/4                                                                       ", // Europe_Sofia
    "CET-1CEST,M3.5.0,M10.5.0/3                                                                         ", // Europe_Stockholm
    "EET-2EEST,M3.5.0/3,M10.5.0/4                                                                       ", // Europe_Tallinn
    "CET-1CEST,M3.5.0,M10.5.0/3                                                                         ", // Europe_Tirane
    "EET-2EEST,M3.5.0,M10.5.0/3                                                                         ", // Europe_Tiraspol
    "<+04>-4                                                                                            ", // Europe_Ulyanovsk
    "EET-2EEST,M3.5.0/3,M10.5.0/4                                                                       ", // Europe_Uzhgorod
    "CET-1CEST,M3.5.0,M10.5.0/3                                                                         ", // Europe_Vaduz
    "CET-1CEST,M3.5.0,M10.5.0/3                                                                         ", // Europe_Vatican
    "CET-1CEST,M3.5.0,M10.5.0/3                                                                         ", // Europe_Vienna
    "EET-2EEST,M3.5.0/3,M10.5.0/4                                                                       ", // Europe_Vilnius
    "<+03>-3                                                                                            ", // Europe_Volgograd
    "CET-1CEST,M3.5.0,M10.5.0/3                                                                         ", // Europe_Warsaw
    "CET-1CEST,M3.5.0,M10.5.0/3                                                                         ", // Europe_Zagreb
    "EET-2EEST,M3.5.0/3,M10.5.0/4                                                                       ", // Europe_Zaporozhye
    "CET-1CEST,M3.5.0,M10.5.0/3                                                                         ", // Europe_Zurich
    "EAT-3                                                                                              ", // Indian_Antananarivo
    "<+06>-6                                                                                            ", // Indian_Chagos
    "<+07>-7                                                                                            ", // Indian_Christmas
    "<+0630>-6:30                                                                                       ", // Indian_Cocos
    "EAT-3                                                                                              ", // Indian_Comoro
    "<+05>-5                                                                                            ", // Indian_Kerguelen
    "<+04>-4                                                                                            ", // Indian_Mahe
    "<+05>-5                                                                                            ", // Indian_Maldives
    "<+04>-4                                                                                            ", // Indian_Mauritius
    "EAT-3                                                                                              ", // Indian_Mayotte
    "<+04>-4                                                                                            ", // Indian_Reunion
    "PST8PDT,M3.2.0,M11.1.0                                                                             ", // Mexico_BajaNorte
    "MST7MDT,M4.1.0,M10.5.0                                                                             ", // Mexico_BajaSur
    "CST6CDT,M4.1.0,M10.5.0                                                                             ", // Mexico_General
    "<+13>-13                                                                                           ", // Pacific_Apia
    "NZST-12NZDT,M9.5.0,M4.1.0/3                                                                        ", // Pacific_Auckland
    "<+11>-11                                                                                           ", // Pacific_Bougainville
    "<+1245>-12:45<+1345>,M9.5.0/2:45,M4.1.0/3:45                                                       ", // Pacific_Chatham
    "<+10>-10                                                                                           ", // Pacific_Chuuk
    "<-06>6<-05>,M9.1.6/22,M4.1.6/22                                                                    ", // Pacific_Easter
    "<+11>-11                                                                                           ", // Pacific_Efate
    "<+13>-13                                                                                           ", // Pacific_Enderbury
    "<+13>-13                                                                                           ", // Pacific_Fakaofo
    "<+12>-12<+13>,M11.2.0,M1.2.3/99                                                                    ", // Pacific_Fiji
    "<+12>-12                                                                                           ", // Pacific_Funafuti
    "<-06>6                                                                                             ", // Pacific_Galapagos
    "<-09>9                                                                                             ", // Pacific_Gambier
    "<+11>-11                                                                                           ", // Pacific_Guadalcanal
    "ChST-10                                                                                            ", // Pacific_Guam
    "HST10                                                                                              ", // Pacific_Honolulu
    "HST10                                                                                              ", // Pacific_Johnston
    "<+13>-13                                                                                           ", // Pacific_Kanton
    "<+14>-14                                                                                           ", // Pacific_Kiritimati
    "<+11>-11                                                                                           ", // Pacific_Kosrae
    "<+12>-12                                                                                           ", // Pacific_Kwajalein
    "<+12>-12                                                                                           ", // Pacific_Majuro
    "<-0930>9:30                                                                                        ", // Pacific_Marquesas
    "SST11                                                                                              ", // Pacific_Midway
    "<+12>-12                                                                                           ", // Pacific_Nauru
    "<-11>11                                                                                            ", // Pacific_Niue
    "<+11>-11<+12>,M10.1.0,M4.1.0/3                                                                     ", // Pacific_Norfolk
    "<+11>-11                                                                                           ", // Pacific_Noumea
    "SST11                                                                                              ", // Pacific_Pago_Pago
    "<+09>-9                                                                                            ", // Pacific_Palau
    "<-08>8                                                                                             ", // Pacific_Pitcairn
    "<+11>-11                                                                                           ", // Pacific_Pohnpei
    "<+11>-11                                                                                           ", // Pacific_Ponape
    "<+10>-10                                                                                           ", // Pacific_Port_Moresby
    "<-10>10                                                                                            ", // Pacific_Rarotonga
    "ChST-10                                                                                            ", // Pacific_Saipan
    "SST11                                                                                              ", // Pacific_Samoa
    "<-10>10                                                                                            ", // Pacific_Tahiti
    "<+12>-12                                                                                           ", // Pacific_Tarawa
    "<+13>-13                                                                                           ", // Pacific_Tongatapu
    "<+10>-10                                                                                           ", // Pacific_Truk
    "<+12>-12                                                                                           ", // Pacific_Wake
    "<+12>-12                                                                                           ", // Pacific_Wallis
    "<+10>-10                                                                                           ", // Pacific_Yap
    "AKST9AKDT,M3.2.0,M11.1.0                                                                           ", // US_Alaska
    "HST10HDT,M3.2.0,M11.1.0                                                                            ", // US_Aleutian
    "MST7                                                                                               ", // US_Arizona
    "CST6CDT,M3.2.0,M11.1.0                                                                             ", // US_Central
    "EST5EDT,M3.2.0,M11.1.0                                                                             ", // US_East_Indiana
    "EST5EDT,M3.2.0,M11.1.0                                                                             ", // US_Eastern
    "HST10                                                                                              ", // US_Hawaii
    "CST6CDT,M3.2.0,M11.1.0                                                                             ", // US_Indiana_Starke
    "EST5EDT,M3.2.0,M11.1.0                                                                             ", // US_Michigan
    "MST7MDT,M3.2.0,M11.1.0                                                                             ", // US_Mountain
    "PST8PDT,M3.2.0,M11.1.0                                                                             ", // US_Pacific
    "SST11                                                                                              ", // US_Samoa
};

void getTZ(TimeZone tz, char * buffer, size_t len) {
    if (!buffer)
        return;
    strncpy_P(buffer, (char *) pgm_read_dword(&(timezoneList[static_cast<int>(tz)])), len);
}
